version: '3'
services:
    app-agendamento:
      container_name: app-agendamento
      build:
        context: ./php8-fpm
      ports:
        - "5173:5173"
      volumes:
        - "./:/var/www/html"
        - "./php8-fpm/config/jit.ini:/usr/local/etc/php/conf.d/jit.ini"
        - ./php8-fpm/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini

    nginx:
      build: ./nginx
      ports:
        - "80:80"
      volumes:
        - "./:/var/www/html"
        - "./nginx/default:/etc/nginx/conf.d/default.conf"
      depends_on:
        - app-agendamento

    mysql:
      image: mariadb:10.2
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - mariadb:/var/lib/mysql

    mongo:
      image: mongo
      container_name: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      ports:
        - "27017:27017"

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        environment:
          - PMA_PORT=3306
          - PMA_HOST=mysql
          - MYSQL_ROOT_PASSWORD=root
          - PMA_USER=root
          - PMA_PASSWORD=root
          - TZ=America/Sao_Paulo
          - UPLOAD_LIMIT=100M
        ports:
          - "8080:80"
        depends_on:
          - mysql

volumes:
    mariadb:
        external: false
